# gsensor drivers

obj-$(CONFIG_SENSORS_MMA7660) 	+= mma7660.o
obj-$(CONFIG_SENSORS_MMA8452) 	+= mma8452.o
obj-$(CONFIG_SENSORS_L3G4200D) 	+= l3g4200d.o
obj-$(CONFIG_SENSORS_LIS3DH)		+= lis3dh.o
obj-$(CONFIG_SENSORS_BMA023) 	+= bma023.o
obj-$(CONFIG_SENSORS_STK8312) 	+= stk831x.o
