#lib-y = Common.o HostComm.o Main.o MemoryMapChipOne.o PeripheralsDriverLib.o TouchCommon.o TouchDataProcessLib.o WorkModeNormal.o
obj-y += icn838x_ts_iic.o
icn838x_ts_iic-objs := icn838x_iic_ts.o icn838x_iic_slave.o lib.a
