/*
 * Automatically generated C config: don't edit
 * Tue Aug 10 19:52:12 2010
 */

/* OSes supported */
#define NMI_WIN32 		0
#define NMI_NU 			1
#define NMI_MTK 		2
#define NMI_LINUX 		3
#define NMI_LINUXKERNEL 	4
/* the current OS */
//#define NMI_PLATFORM NMI_LINUXKERNEL


/* Logs options */
#define NMI_LOGS_NOTHING          0
#define NMI_LOGS_WARN             1
#define NMI_LOGS_WARN_INFO        2
#define NMI_LOGS_WARN_INFO_DBG    3
#define NMI_LOGS_WARN_INFO_DBG_FN 4
#define NMI_LOGS_ALL              5

#define NMI_LOG_VERBOSITY_LEVEL NMI_LOGS_ALL

/* OS features supported */

#define CONFIG_NMI_THREAD_FEATURE 1
//#define CONFIG_NMI_THREAD_SUSPEND_CONTROL 1
//#define CONFIG_NMI_THREAD_STRICT_PRIORITY 1
#define CONFIG_NMI_SEMAPHORE_FEATURE 1
//#define CONFIG_NMI_SEMAPHORE_TIMEOUT 1
#define CONFIG_NMI_SLEEP_FEATURE 1
#define CONFIG_NMI_SLEEP_HI_RES 1
#define CONFIG_NMI_TIMER_FEATURE 1
//#define CONFIG_NMI_TIMER_PERIODIC 1 
#define CONFIG_NMI_MEMORY_FEATURE 1
//#define CONFIG_NMI_MEMORY_POOLS 1 
//#define CONFIG_NMI_MEMORY_DEBUG 1
//#define CONFIG_NMI_ASSERTION_SUPPORT 1
#define CONFIG_NMI_STRING_UTILS 1
#define CONFIG_NMI_MSG_QUEUE_FEATURE
//#define CONFIG_NMI_MSG_QUEUE_IPC_NAME
//#define CONFIG_NMI_MSG_QUEUE_TIMEOUT
//#define CONFIG_NMI_FILE_OPERATIONS_FEATURE
//#define CONFIG_NMI_FILE_OPERATIONS_STRING_API
//#define CONFIG_NMI_FILE_OPERATIONS_PATH_API
#define CONFIG_NMI_TIME_FEATURE
//#define CONFIG_NMI_EVENT_FEATURE
//#define CONFIG_NMI_EVENT_TIMEOUT
//#define CONFIG_NMI_SOCKET_FEATURE
//#define CONFIG_NMI_MATH_OPERATIONS_FEATURE
//#define CONFIG_NMI_EXTENDED_FILE_OPERATIONS
//#define CONFIG_NMI_EXTENDED_STRING_OPERATIONS
//#define CONFIG_NMI_EXTENDED_TIME_OPERATIONS
